### ISSUE TITLE
Clean up overflow in list component rows

### ISSUE THREAD

**Issue by abwilson23** [MauroDataMapper/mdm-explorer#393] opened 2024-05-02 13:46 UTC
The data in the list components will overflow into each other causing a messy ui (as shown below). 
Proppose either ellipses/space dividers with a hover to display the data in cases where there is overflow. 
Ultimately these changes will live in sde-resources and any changes will need to be checked in the sde-admin-ui too. 

Likely, this will just involve tweaking the list component. 

![image](https://github.com/MauroDataMapper/mdm-explorer/assets/6440992/d3bb9464-b2bd-4ff3-8a0d-2442b314ea90)

**Comment by NigelPalmer** [comment] 2024-08-28 07:40
This is a duplicate of maurodatamapper/sde-resources#64

**Closed as completed by NigelPalmer** 2024-08-28 07:40 UTC
Labels: enhancement
