### ISSUE TITLE
Spinner for Removal of data elements in requests does not end

### ISSUE THREAD

**Issue by OButlerOcc** [MauroDataMapper/mdm-explorer#284] opened 2023-02-21 11:36 UTC
To Replicate:
Create a request.
Add some data elements.
Remove a data element individually or via selection ticks and remove selected.

The Spinner appears with "removing x items" 
The spinner never closes.
Refresh the page. 
The items are removed sucessfully.

**Comment by OButlerOcc** [comment] 2023-02-21 11:36
![image](https://user-images.githubusercontent.com/85611988/220334790-f07f9c0a-642e-4113-bc10-52efec118dd1.png)

**Comment by pjmonks** [comment] 2023-02-22 15:19
I think this is a duplicate of #285 so I will close this issue.

**Closed by pjmonks** 2023-02-22 15:19 UTC
Labels: bug
